language: ruby
rvm:
- 2.4.2
install:
- bundle install --local --jobs=3 --retry=3 --deployment
deploy:
  provider: heroku
  api_key:
    secure: FMgS032IVyicl7HAFrsWv7pDmcA+nDMgxGzaovg0uDfk2yjSYcoeSwlnFeMVjdIR3tgibT6/Awg4CkhrjAw5cBKJFHrFG0ND1MeA53sFtpTdEpU5O4Wwdt2YJOO6HJ9NSWR39Cq9++6zcl7kLkc1KcHuPWWtRf/xRhKEfaww5Cc=
  app: canadiaweather
env:
  global:
    secure: hqhrpC91wSsyT24BKT2NM+tUaEVC+RX2gV5IjwjqxyAU2iWQfeRXJ8PC8SxSJc50Vjo+paejX0JlEycd415AVFXTl/iY+QUZaFQSuTdCxR+6+ggf5F6ytm7QvkxLE/Ttc5FWGpF2Bxj95aAVryP8LYZJDoTlZlWe0FlzIfwTml4=
